gearbox_client:
    resource: "@GearboxClientBundle/Resources/config/routing.yml"
    prefix:   /

gearbox_api_security:
    resource: "@GearboxSecurityBundle/Resources/config/routing.yml"
    prefix:   /